# Generated by Django 3.2.13 on 2022-06-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_diary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
